name: Incoming PR
run-name: PR opened by ${{ github.actor }}

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  run-snowflake-test-dbt-job:
    name: "Run on Incoming PR"
    runs-on: ubuntu-latest
    environment: prod # Must match the OIDC subject's environment

    env:
      SNOWFLAKE_CLI_FEATURES_ENABLE_DBT: true
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }} # if not using OIDC
      SNOWFLAKE_DATABASE: ${{ secrets.DEV_SNOWFLAKE_DATABASE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v2.0
        with:
          use-oidc: true

      - name: Check Snowflake CLI Version
        run: snow --version

      - name: Test Snowflake connection
        run: snow connection test -x

      - name: dbt build (DEV)
        working-directory: dbt_lakehouse_pharma
        run: dbt build --target dev
