name: dbt CI

on:
  pull_request:
    branches: [ main ]

jobs:
  dbt-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dbt + Snowflake adapter
        run: |
          pip install --upgrade pip
          pip install dbt-core dbt-snowflake snowflake-connector-python

      - name: Setup dbt profiles
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOF
          dbt_dev_lakehouse_pharma:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: $SNOWFLAKE_ACCOUNT
                user: $SNOWFLAKE_USER
                password: $SNOWFLAKE_PASSWORD
                role: ACCOUNTADMIN
                warehouse: COMPUTE_WH
                database: DEV_LAKEHOUSE
                schema: BRONZE
                threads: 8
          EOF
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

      - name: dbt deps
        working-directory: dbt_lakehouse_pharma
        run: dbt deps

      - name: dbt build (DEV)
        working-directory: dbt_lakehouse_pharma
        run: dbt build --target dev
