name: Incoming PR
run-name: PR opened by ${{ github.actor }}

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  run-snowflake-test-dbt-job:
    name: "Run on Incoming PR"
    runs-on: ubuntu-latest
    environment: prod

    env:
      SNOWFLAKE_CLI_FEATURES_ENABLE_DBT: true
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_DATABASE: ${{ secrets.DEV_SNOWFLAKE_DATABASE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v2.0
        with:
          use-oidc: true

      - name: Check Snowflake CLI Version
        run: snow --version

      - name: Test Snowflake connection
        run: snow connection test -x
      - name: Create a new tester dbt project object in ${{ secrets.SNOWFLAKE_DATABASE }}.${{ secrets.SNOWFLAKE_SCHEMA  }}
        working-directory: dbt_lakehouse_pharma
        run: snow dbt deploy dbt_lakehouse_pharma_action --dbt-version 1.10.15 --force -x
      - name: List all of the snowflake dbt project objects in your account
        working-directory: dbt_lakehouse_pharma
        run: snow dbt list -x
        # Builds all models and runs tests in DAG order, failing early if any upstream test breaks
      - name: Debug current role 1
        working-directory: dbt_lakehouse_pharma
        run: snow sql -x -q "SELECT CURRENT_ROLE();"
      - name: Debug current role 2
        working-directory: dbt_lakehouse_pharma
        run: |
          snow sql -x -q "SELECT 
          CURRENT_USER(),
          CURRENT_ROLE(),
          CURRENT_SECONDARY_ROLES(),
          CURRENT_DATABASE(),
          CURRENT_SCHEMA(),
          CURRENT_WAREHOUSE();"
      - name: Debug current role 3
        working-directory: dbt_lakehouse_pharma
        run: snow sql -x -q "SELECT CURRENT_USER();"
        
      - name: Build and test dbt project in ${{ secrets.SNOWFLAKE_DATABASE }}.${{ secrets.SNOWFLAKE_SCHEMA }}
        working-directory: dbt_lakehouse_pharma
        run: snow dbt execute -x dbt_lakehouse_pharma_action build --target dev
