name: dbt Deploy PROD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dbt
        run: |
          pip install dbt-core dbt-snowflake

      - name: Setup profiles
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.DBT_PROFILES }}" > ~/.dbt/profiles.yml

      - name: dbt deps
        run: dbt deps

      - name: Deploy to PROD
        run: dbt build --target prod
